Business feature
E-F-III/tapiru pull request #54
Opened 2023-03-31 02:23 UTC by hazeluwuz

2023-03-31 02:33 UTC, E-F-III requested changes

2023-03-31 02:33 UTC, E-F-III commented on app/api/business_routes.py
> +
Error response with status 404 is given when a business does not exist with the provided id

2023-03-31 02:33 UTC, E-F-III commented on app/api/business_routes.py
> +    return {'errors': validation_errors_to_error_messages(form.errors)}, 401
StatusCode 401 = Unauthroized

400 for bad request

2023-03-31 02:33 UTC, E-F-III commented on app/api/business_routes.py
> +    return {'errors': validation_errors_to_error_messages(form.errors)}, 401
StatusCode 401 = Unauthroized

400 for bad request

2023-03-31 02:33 UTC, E-F-III commented on app/api/business_routes.py
> +    business_to_edit = Business.query.get(businessId)
Check if business exists - 404

Check if current user is the owner of the business before editing - 401

2023-03-31 02:33 UTC, E-F-III commented on app/api/business_routes.py
> +
Check if business exists - 404

2023-04-05 19:46 UTC, rudyn2010 commented
for review - ed

2023-04-17 21:55 UTC, E-F-III requested changes

2023-04-17 21:55 UTC, E-F-III commented on app/models/businesses.py
payment types not a column on business table. will come as associated data

2023-04-17 21:55 UTC, E-F-III commented on app/api/business_routes.py
> +    return {'errors': validation_errors_to_error_messages(form.errors)}, 401
error 400 for body validation errors!

2023-04-19 19:14 UTC, E-F-III approved these changes

2023-04-19 19:14 UTC, merged